In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [3]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
arr = np.array(my_mat) # 2D Array
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(1,5)

array([1, 2, 3, 4])

In [8]:
np.arange(4,10,2)

array([4, 6, 8])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [15]:
np.eye(3) # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.random.rand(5)

array([0.72741045, 0.82740823, 0.93607308, 0.5486666 , 0.04721606])

In [18]:
np.random.rand(3,4)

array([[0.68148371, 0.63496653, 0.38911378, 0.51603581],
       [0.0063059 , 0.0919928 , 0.210052  , 0.19005047],
       [0.22945889, 0.05790246, 0.90023407, 0.12609667]])

In [20]:
np.random.randint(1,50,5)

array([37, 44, 11, 26, 32])

In [25]:
arr2 = np.arange(25)

In [26]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
arr3 = arr2.reshape(5,5)

In [28]:
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
arr3.max()

24

In [30]:
arr.min()

1

In [31]:
arr3.argmax()

24

In [32]:
arr.argmax()

8

In [34]:
my_arr = np.arange(0,11)
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
my_arr[1:3]

array([1, 2])

In [37]:
my_arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
my_arr[0:5] = 100
my_arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [39]:
slice_of_arr = my_arr[6:9]
slice_of_arr

array([6, 7, 8])

In [40]:
slice_of_arr[:] = 0
slice_of_arr

array([0, 0, 0])

In [41]:
my_arr

array([100, 100, 100, 100, 100,   5,   0,   0,   0,   9,  10])

In [42]:
my_arr_copy = my_arr.copy()

In [44]:
my_arr_copy[:] = 15
my_arr_copy

array([15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15])

In [46]:
arr_2d = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [47]:
arr_2d[0][0]  # 1st row , 1st column

10

In [48]:
arr_2d[0]

array([10, 20, 30])

In [51]:
arr_2d[2,2] 

90

In [52]:
arr_2d[:2,1:]

array([[20, 30],
       [50, 60]])

In [53]:
arr_2d[:2,2:]

array([[30],
       [60]])

In [54]:
new_arr = np.arange(0,10)
new_arr[new_arr<4]

array([0, 1, 2, 3])

In [56]:
arr_3d = np.arange(50).reshape(5,10)
arr_3d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [60]:
# Grabbing 14,15 and 45,46,47

arr_3d[1,4:6]

array([14, 15])

In [2]:
import numpy as np

In [5]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
a+a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
a*a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [9]:
a + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [11]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [12]:
a.max()

10

In [13]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [14]:
np.log(a)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [19]:
np.ones(5)+4

array([5., 5., 5., 5., 5.])

In [23]:
d=np.random.rand(100)

In [24]:
d.sum()

56.03326731618671

In [25]:
d.std()

0.29057226218719273

In [34]:
e = np.random.rand(2,3)
e

array([[0.52547336, 0.34537553, 0.21222814],
       [0.02388368, 0.06085388, 0.49656997]])

In [37]:
e.sum(axis=1) # rows

array([1.08307703, 0.58130753])

In [38]:
e.sum(axis=0) # columns

array([0.54935703, 0.40622941, 0.70879811])